### ISSUE TITLE
MOD Updates / wiped functions

### ISSUE THREAD

**Issue by ThisIsTheGitHubAccount4MUHAKL** [Minecolonies/minecolonies#276]
### Minecolonies version
MC version 1.10.2 , Single Player
version minecolonies-universal-**1.10.2-0.4.1711**.jar

Please confirm 
CREATIV  MODE
1                 WAREHOUSE has been wiped out by updates
2                 QUARRY is NOT IMPLEMENTED
3                 FORGE has been wiped out by updates
3                 BAKERY has been wiped out by updates

GENERAL 
5                 The CITIZEN HUT lev. 5 has changed from STONE to WOOD
6                 Toggle Specialisation Butten is just decoration 
7                 Schematic preview is different than finished building ( location offset / rotated )      

 I love the mod, build my machines into HUT's level 5, even AE rv4, and looking foreward 
to have all functions avaliable in SURVIVAL mode.

respect for the modders,
MUHAKL

**Comment by Kostronor** [comment]
1,2,3,4 not implemented 
5 elaborate please 
6 not implemented 
7 should be fixed with newest version we will upload today or so. Working on it

**Comment by Raycoms** [comment]
5: We have added a complete wooden style for now. We're planning on adding stone, sandstone etc builds later.
7: Should be working correctly now.

Open a new one for 7 if not resolved and show how to reproduce it.
